### ISSUE TITLE
Senzing command line programs

### ISSUE THREAD

**Issue by christianswanepoel** [Senzing/docker-sshd#6]
I implemented the advanced version of docker-compose-aws-ecscli-demo and expected G2Command.py run in docker-sshd - but it is not? Would this be hard to implement or what are my alternatives?

**Comment by docktermj** [comment]
@SamMacy We want to figure out why `G2Command.py` isn't working. 
Reference: https://github.com/Senzing/docker-compose-aws-ecscli-demo/issues/37

**Comment by docktermj** [comment]
Pull Requests

1. https://github.com/Senzing/docker-sshd/pull/7
